- name: install catalogue componenet
  hosts: catalogue
  become: yes
  tasks:
  - name: setup npm sorce
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"
  - name: install node js
    ansible.builtin.yum:
     name: nodejs
     state: installed
  
  - name: check existence of roboshop user
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true

  - when: out.rc != 0
    name: create user roboshop
    ansible.builtin.user:
      name: roboshop

  - name: check /app directory exists or not
    ansible.builtin.stat:
      path: /app
    register: directory
  
  - when: directory.stat.exists == False
    name: create a directory if it doesnot exist
    ansible.builtin.file:
      path: /app
      state: directory
      mode: '0755'
